package fr.tikione.jacocoverage.plugin.config;

import fr.tikione.jacocoverage.plugin.util.NBUtils;
import java.awt.Dimension;
import java.awt.Toolkit;

public class AboutDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        final int screenWidth = screenSize.width;
        final int screenHeight = screenSize.height;
        int posX = (screenWidth / 2) - (this.getWidth() / 2);
        int posY = (screenHeight / 2) - (this.getHeight() / 2);
        this.setBounds(posX, posY, this.getWidth(), this.getHeight());
        jLabelAbout.setText("<html>Copyright © 2013 Jonathan Lermitage &lt;jonathan.lermitage@gmail.com&gt;<br>\n"
                + "This work is free. You can redistribute it and/or modify it under the\n"
                + "terms of the Do What The Fuck You Want To Public License, Version 2,\n"
                + "as published by Sam Hocevar. See http://www.wtfpl.net for more details.</html>");
        jButtonSeeWTFPL.setToolTipText("<html><body>Visit the <b>WTFPL</b> website<br>http://www.wtfpl.net</body></html>");
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAbout = new javax.swing.JLabel();
        jButtonSeeWTFPL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(AboutDialog.class, "AboutDialog.title")); // NOI18N
        setResizable(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelAbout, org.openide.util.NbBundle.getMessage(AboutDialog.class, "AboutDialog.jLabelAbout.text")); // NOI18N
        jLabelAbout.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonSeeWTFPL.setForeground(new java.awt.Color(0, 51, 204));
        jButtonSeeWTFPL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fr/tikione/jacocoverage/plugin/resources/icon/wtfpl.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonSeeWTFPL, org.openide.util.NbBundle.getMessage(AboutDialog.class, "AboutDialog.jButtonSeeWTFPL.text")); // NOI18N
        jButtonSeeWTFPL.setToolTipText(org.openide.util.NbBundle.getMessage(AboutDialog.class, "AboutDialog.jButtonSeeWTFPL.toolTipText")); // NOI18N
        jButtonSeeWTFPL.setBorder(null);
        jButtonSeeWTFPL.setBorderPainted(false);
        jButtonSeeWTFPL.setContentAreaFilled(false);
        jButtonSeeWTFPL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeeWTFPL.setFocusPainted(false);
        jButtonSeeWTFPL.setFocusable(false);
        jButtonSeeWTFPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeWTFPLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonSeeWTFPL, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jButtonSeeWTFPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeeWTFPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeWTFPLActionPerformed
        NBUtils.extBrowser("http://www.wtfpl.net");
    }//GEN-LAST:event_jButtonSeeWTFPLActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSeeWTFPL;
    private javax.swing.JLabel jLabelAbout;
    // End of variables declaration//GEN-END:variables
}
