package fr.tikione.jacocoverage.plugin.config;

import fr.tikione.jacocoverage.plugin.util.NBUtils;
import java.io.File;
import java.io.IOException;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JRadioButton;
import javax.swing.LayoutStyle;
import org.netbeans.api.project.Project;
import org.openide.awt.Mnemonics;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;

public class JPanelPrjcfgAntJavase extends javax.swing.JPanel implements IStorable {

    private static final long serialVersionUID = 1L;

    private File prjCfgFile;

    /**
     * Creates new form JPanelPrjcfgAntJavase.
     *
     * @param context
     */
    public JPanelPrjcfgAntJavase(Lookup context) {
        super();
        initComponents();
        Project project = NBUtils.getSelectedProject();
        prjCfgFile = new File(NBUtils.getProjectDir(project), Globals.PRJ_CFG);
        load();
    }

    private void load() {
        try {
            ProjectConfig prjCfg = ProjectConfig.forFile(prjCfgFile);
            jRadioButtonUseGlobalOptions.setSelected(!prjCfg.isOverrideGlobals());
            jRadioButtonUseProjectSpecificOptions.setSelected(prjCfg.isOverrideGlobals());
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    @Override
    public void store() {
        try {
            ProjectConfig prjCfg = ProjectConfig.forFile(prjCfgFile);
            prjCfg.setOverrideGlobals(jRadioButtonUseProjectSpecificOptions.isSelected());
            prjCfg.store();
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupUseGlobalOptions = new ButtonGroup();
        jRadioButtonUseGlobalOptions = new JRadioButton();
        jRadioButtonUseProjectSpecificOptions = new JRadioButton();

        buttonGroupUseGlobalOptions.add(jRadioButtonUseGlobalOptions);
        Mnemonics.setLocalizedText(jRadioButtonUseGlobalOptions, NbBundle.getMessage(JPanelPrjcfgAntJavase.class, "JPanelPrjcfgAntJavase.jRadioButtonUseGlobalOptions.text")); // NOI18N

        buttonGroupUseGlobalOptions.add(jRadioButtonUseProjectSpecificOptions);
        Mnemonics.setLocalizedText(jRadioButtonUseProjectSpecificOptions, NbBundle.getMessage(JPanelPrjcfgAntJavase.class, "JPanelPrjcfgAntJavase.jRadioButtonUseProjectSpecificOptions.text")); // NOI18N

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonUseGlobalOptions)
                    .addComponent(jRadioButtonUseProjectSpecificOptions))
                .addGap(0, 288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jRadioButtonUseGlobalOptions)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonUseProjectSpecificOptions)
                .addGap(0, 256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroupUseGlobalOptions;
    private JRadioButton jRadioButtonUseGlobalOptions;
    private JRadioButton jRadioButtonUseProjectSpecificOptions;
    // End of variables declaration//GEN-END:variables
}
